[repo]
local_olive_dir="$HOME/code/analysis-config"
main="main"
workflow_repo_url="https://github.com/oicr-gsi"
organization="oicr-gsi"
token="ADD_YOUR_OWN"

[instances]
instance_a="research"
instance_b="clinical"

[prefixes]
call_prefix_a="call_ready"
call_prefix_b="lane_level"
call_prefix_c="tumor_only"
call_prefix_d="matched"
call_prefix_e="bytumorgroup"
call_prefix_f="bysample"
call_prefix_g="by_tumor_group"
call_prefix_h="tumor_group"
call_prefix_i="by_sample"
call_prefix_k="filter_only"
call_prefix_n="normal_only"
call_prefix_o="MiSeq"
call_prefix_p="CM"
call_prefix_r="TS"
call_prefix_s="fastq"
call_prefix_t="bam"
call_prefix_u="miseq"

[aliases]
clinical="production-cap"
bmpp="bamMergePreprocessing"






